apiVersion: v1
kind: Service
metadata:
  name: ms-mfs
  labels:
    app: ms-mfs
    visualize: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: ms-mfs